info help:  ## Shows the commands + comments below
	@grep -E '^([a-zA-Z_-])+[^:]+:.*?## (.*)$$' $(MAKEFILE_LIST) | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'

clean: ## Cleans autogenerated files
	rm -rf dist
	find . -type f -name "*.DS_Store" -ls -delete
	find . | grep -E "(__pycache__|\.pyc|\.pyo)" | xargs rm -rf
	find . | grep -E ".pytest_cache" | xargs rm -rf
	find . | grep -E ".ipynb_checkpoints" | xargs rm -rf
	rm -f .coverage
	rm -rf htmlcov
	rm -rf logs/coverage
	pre-commit clean

check checks: ## Runs pre-commit hooks (cleanups, auto-reformats, ...)
	pre-commit run -a

test tests: ## Runs not-slow tests using pytest
	pytest -k "not slow"

test-all tests-all: ## Runs all tests (including slow ones) w/ verbose to see warnings
	pytest -v

coverage cov: ## Runs tests with coverage; artifacts saved under logs/coverage
	mkdir -p logs/coverage
	pytest -k "not slow" \
		--cov=pyine \
		--cov-branch \
		--cov-report=term-missing \
		--cov-report=html:logs/coverage/html \
		--cov-report=xml:logs/coverage/coverage.xml \
		2>&1 | tee logs/coverage/coverage.log

coverage-all cov-all: ## Runs tests with coverage (including slow ones)
	mkdir -p logs/coverage
	pytest -v \
		--cov=pyine \
		--cov-branch \
		--cov-report=term-missing \
		--cov-report=html:logs/coverage/html \
		--cov-report=xml:logs/coverage/coverage.xml \
		2>&1 | tee logs/coverage/coverage.log

clean-coverage: ## Removes only coverage artifacts (keeps other logs)
	rm -rf logs/coverage
	rm -f .coverage
	rm -rf htmlcov

stats: ## Shows a quick snapshot of git activity and tracked files
	@echo "=== Git Status ==="
	@git rev-parse --abbrev-ref HEAD | awk '{print "Active branch: " $$1}'
	@git log -1 --pretty="Last commit: %h %cr %an - %s"
	@git rev-list --count HEAD | awk '{print "Total commits: " $$1}'
	@git shortlog -s -n --all | wc -l | awk '{print "Contributors: " $$1}'
	@echo ""
	@echo "=== Recent Activity ==="
	@git log --since="7 days ago" --oneline | wc -l | awk '{print "Commits (last 7 days): " $$1}'
	@git log --since="30 days ago" --oneline | wc -l | awk '{print "Commits (last 30 days): " $$1}'
	@echo ""
	@echo "=== Code Churn (last 30 days) ==="
	@git log --since="30 days ago" --pretty=tformat: --numstat | awk '{adds+=$$1; dels+=$$2} END {printf "Insertions: %d\nDeletions: %d\nNet change: %+d\n", adds, dels, adds-dels}'
	@echo ""
	@echo "=== Repository Info ==="
	@git ls-files | wc -l | awk '{print "Tracked files: " $$1}'
	@du -sh .git 2>/dev/null | awk '{print "Repository size: " $$1}' || echo "Repository size: N/A"
	@echo ""
	@echo "=== Lines of Code ==="
	@printf '%s\n' \
		"import collections" \
		"import pathlib" \
		"import subprocess" \
		"" \
		"repo_root = pathlib.Path().resolve()" \
		"result = subprocess.run(['git', 'ls-files'], check=True, text=True, capture_output=True)" \
		"counts = collections.Counter()" \
		"dir_counts = collections.Counter()" \
		"total = 0" \
		"for relative_path in result.stdout.splitlines():" \
		"    path = repo_root / relative_path" \
		"    if not path.exists() or path.is_dir():" \
		"        continue" \
		"    try:" \
		"        with path.open('r', encoding='utf-8', errors='ignore') as handle:" \
		"            file_loc = sum(1 for _ in handle)" \
		"    except OSError:" \
		"        continue" \
		"    suffix = path.suffix.lower()" \
		"    if not suffix:" \
		"        suffix = '<no-ext>'" \
		"    counts[suffix] += file_loc" \
		"    total += file_loc" \
		"    " \
		"    # Track top-level directory" \
		"    parts = pathlib.Path(relative_path).parts" \
		"    if len(parts) > 1:" \
		"        dir_counts[parts[0]] += 1" \
		"    else:" \
		"        dir_counts['<root>'] += 1" \
		"" \
		"print(f'Total tracked lines: {total}')" \
		"print(f'By file type:')" \
		"for suffix, value in counts.most_common(10):" \
		"    pct = 100 * value / total if total > 0 else 0" \
		"    print(f'  {suffix:>10}: {value:>7} ({pct:>5.1f}%)')" \
		"" \
		"if len(counts) > 10:" \
		"    print(f'  ... and {len(counts) - 10} more')" \
		"" \
		"print(f'\\nFiles by directory:')" \
		"for dirname, count in dir_counts.most_common(10):" \
		"    print(f'  {dirname:>15}: {count:>4} files')" \
	| python -
