[project]
name = "pyine"
version = "0.1.0"
readme = "README.md"
description = "Python Interpretation and Execution (PyINE) dataset and benchmark framework"
keywords = ["benchmarking", "python", "interpretation", "execution", "llm", "nlp"]
authors = [
    { name = "Pierre-Luc St-Charles", email = "pl.stcharles@lawzero.org" }
]
#license = "TBD"  # @@@@@ TODO
requires-python = ">=3.12,<3.13"
dependencies = [
    # last review/update of versions: 2025-08-23
    "accelerate>=1.10.0,<2.0.0",
    "backoff>=2.2.1,<3.0.0",
    "black>=25.1.0,<26.0.0",
    "blobfile>=3.0.0,<4.0.0",
    "datasets>=4.0.0,<5.0.0",
    "deepdiff>=8.6.0,<9.0.0",
    "evaluate>=0.4.5,<1.0.0",
    "gitpython>=3.1.45,<4.0.0",
    "hydra-colorlog>=1.2.0,<2.0.0",
    "hydra-core>=1.3.2,<1.4.0",
    "hydra-zen>=0.15.0,<1.0.0",
    "Levenshtein>=0.27.1,<0.28.0",
    "langchain>=0.3.27,<0.4.0",
    "langchain_deepseek>=0.1.4,<0.2.0",
    "langchain-huggingface>=0.3.1,<1.0.0",
    "lightning>=2.5.3,<2.6.0",
    "lmdb>=1.7.3,<2.0.0",
    "lz4>=4.4.4,<5.0.0",
    "matplotlib>=3.10.5,<4.0.0",
    "msgspec>=0.19.0,<0.20.0",
    "numpy>=2.3.2,<3.0.0",
    "openai>=1.101.0,<2.0.0",
    "orjson>=3.11.2,<3.12.0",
    "pandas>=2.3.2,<3.0.0",
    "peft>=0.17.1,<1.0.0",
    "pydantic>=2.11.7,<3.0.0",
    "python-dotenv>=1.1.1,<2.0.0",
    "python-minifier>=2.11.3,<3.0.0",
    "rich>=14.1.0,<15.0.0",
    "tiktoken>=0.11.0,<1.0.0",
    "torch>=2.8.0,<3.0.0",
    "tqdm>=4.67.1,<5.0.0",
    "transformers>=4.55.4,<5.0.0",
    "trl>=0.21.0,<1.0.0",
    "unidiff>=0.7.5,<0.8.0",
    "wandb>=0.21.1,<1.0.0",
    # @@@@ TODO: add install instructions for flash-attn?
]

[project.optional-dependencies]
dev = [
    "coverage[toml]>=7.10.0",
    "flake8>=7.3.0",
    "isort>=6.0.1",
    "ipython>=8.0.0,<9.0.0",
    "ipywidgets>=8.1.0,<9.0.0",
    "notebook>=7.3.0,<8.0.0",
    "pre-commit>=4.3.0,<5.0.0",
    "pytest>=8.0.0",
    "pytest-asyncio>=1.1.0",
    "pytest-mock>=3.14",
    "pytest-cov>=6.2.0",
    "pytest-timeout>=2.4.0",
    "wordcloud>=1.9.4",
]

[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools]
packages = ["pyine"]

[tool.setuptools.package-data]
"pyine" = ["**/*.yaml"]

[tool.pytest.ini_options]
markers = [
    "slow: marks tests as slow to run due to data/compute (deselect with '-m \"not slow\"')",
]
filterwarnings = [
    # until hydra-zen fixes their deprecation warnings, we need this (currently using 0.15.0)
    'ignore:The `__fields__` attribute is deprecated, use `model_fields` instead\.:pydantic.warnings.PydanticDeprecatedSince20:hydra_zen\.structured_configs\._implementations',
]

[tool.coverage.run]
branch = true
parallel = true
source = ["pyine"]
data_file = "logs/coverage/.coverage"
omit = [
  "tests/*",
  "**/__init__.py",
]

[tool.coverage.report]
skip_covered = true
show_missing = true
exclude_lines = [
  "pragma: no cover",
  'if __name__ == "__main__":',
  "raise NotImplementedError",
]

[tool.coverage.html]
directory = "logs/coverage/html"

[tool.coverage.xml]
output = "logs/coverage/coverage.xml"

[tool.isort]
profile = "black"
line_length = 120
src_paths = ["pyine"]
known_first_party = ["pyine"]

[tool.black]
line-length = 100
target-version = ["py312"]

[tool.nbqa]
files = "^notebooks/"
[tool.nbqa.addopts]
black = ["--line-length=120"]
isort = ["--profile=black"]
flake8 = [
  "--extend-ignore=E203,E402,E501,F401,F841,RST2,RST301",
  "--exclude=logs/*,data/*,build/*,docs/*",
]
