datamodule_class_path: pyine.organisms.datamodules.shortcuts.ShortcutBiasDataModule
datamodule_name: shortcuts_TACO_10s10t_v1_part1to4
lmdb_paths:
- /scratch/a.palmas/code-interp-benchmark/data/traces/TACO/v1.5/10s10t.000001of000026.2025-12-10.lmdb
- /scratch/a.palmas/code-interp-benchmark/data/traces/TACO/v1.5/10s10t.000002of000026.2025-12-10.lmdb
- /scratch/a.palmas/code-interp-benchmark/data/traces/TACO/v1.5/10s10t.000003of000026.2025-12-10.lmdb
- /scratch/a.palmas/code-interp-benchmark/data/traces/TACO/v1.5/10s10t.000004of000026.2025-12-11.lmdb
split_file_path: /scratch/a.palmas/code-interp-benchmark/data/splits/TACO-split.bin
split_seed: 0
base_filter_rule: ''
prompt_config:
  prompt_name: code_execution
  use_chat_template: false
  include_examples: false
  target_examples: null
  version: grpo_minimal
default_dataparser_config:
  class_path: pyine.organisms.datamodules.samples.builder.SampleBuilder
  params:
    filtering_config: {}
    selection_config:
      seed: 0
      allow_db_lookups: true
      code_type_prob_map:
        original: 1.0
      samples_per_family: 1
      draw_attempts: 5
      fallback_to_orig: false
    transform_config:
      seed: 0
      transform_strategy: never
dataparser_config_overrides:
  train:
    filtering_config: {}
    selection_config:
      code_type_prob_map:
        original: 1.0
      samples_per_family: 1
      draw_attempts: 5
      fallback_to_orig: true
    transform_config:
      transform_strategy: never
  valid:
    filtering_config: {}
    selection_config:
      code_type_prob_map:
        original: 1.0
      samples_per_family: 1
      draw_attempts: 5
      fallback_to_orig: true
    transform_config:
      transform_strategy: never
dataloader_config_overrides:
  train:
    shuffle: true
keep_generated_datasets_in_memory: false
subset_names:
- train
- valid
- test
train_subset_names:
- train
valid_subset_names:
- valid
eval_subset_names:
- train
- valid
instantiate_parsers_at_setup: false
use_local_dataset_cache: true
use_tokenized_dataset_cache: true
cache_lock_timeout_seconds: 1800.0
message_generator_num_workers: 4
min_samples_with_hints: 0
min_samples_without_hints: 0
