"""Implements a trace data sample builder compatible with the classic PyTorch dataset interface."""

from __future__ import annotations

import collections
import collections.abc
import logging
import pathlib
import sys
import typing

import torch

import pyine.data.traces.dataset_reader
import pyine.data.traces.dataset_utils
import pyine.organisms.datamodules.samples.common
import pyine.organisms.datamodules.samples.configs
import pyine.prompts

__all__ = [
    "SampleBuilder",
]

logger = logging.getLogger(__name__)

# Use TYPE_CHECKING to help pyright understand the module type while using sys.modules at runtime
# (sys.modules is needed to avoid circular import issues with the attribute chain)
if typing.TYPE_CHECKING:
    _samples_common = pyine.organisms.datamodules.samples.common
else:
    _samples_common = sys.modules["pyine.organisms.datamodules.samples.common"]


class SampleBuilder(torch.utils.data.Dataset[_samples_common.SampleData]):
    """Wrapper around the LMDB trace dataset reader(s) that returns code execution samples.

    The role of this class is to provide trace filtering, sample selection, and transformation
    strategies to build training/evaluation samples from raw execution traces. By 'filtering',
    we mean the strategy used to skip/ignore some traces based on e.g. overall length or length
    of input/output arguments. By 'selection', we mean the strategy used to select which traces to
    use to generate samples (i.e. those augmented with hints/issues or not). By 'transformation',
    we mean the strategy used to transform a raw execution trace into a set of inputs and
    expected output variables to be predicted by a model.

    Note that the samples generated by this class may vary across epochs; if you want to always
    generate the same examples, make sure to fix all config seeds, and avoid updating the epoch
    number at all.
    """

    def __init__(
        self,
        source_data: pyine.data.traces.dataset_reader.DatasetOrDatasetPathObjectOrArray,
        traces: (list[pyine.data.traces.dataset_utils.TraceMetadata] | None) = None,  # if none, targets all
        filtering_config: (
            pyine.organisms.datamodules.samples.configs.TraceFilteringConfig | dict[str, typing.Any] | None
        ) = None,
        selection_config: (
            pyine.organisms.datamodules.samples.configs.SampleSelectionConfig | dict[str, typing.Any] | None
        ) = None,
        transform_config: (
            pyine.organisms.datamodules.samples.configs.SampleTransformConfig | dict[str, typing.Any] | None
        ) = None,
        prompt_result_db_path: str | None = None,  # if none, will use framework default
    ) -> None:
        """Initializes the reader with a list of LMDB readers and a list of target traces."""
        self._curr_epoch: int = 0
        if filtering_config is None:
            filtering_config = pyine.organisms.datamodules.samples.configs.TraceFilteringConfig()
        elif isinstance(filtering_config, dict):
            filtering_config = pyine.organisms.datamodules.samples.configs.TraceFilteringConfig(**filtering_config)
        self.filtering_config = filtering_config
        if selection_config is None:
            selection_config = pyine.organisms.datamodules.samples.configs.SampleSelectionConfig()
        elif isinstance(selection_config, dict):
            selection_config = pyine.organisms.datamodules.samples.configs.SampleSelectionConfig(**selection_config)
        self.selection_config = selection_config
        if transform_config is None:
            transform_config = pyine.organisms.datamodules.samples.configs.SampleTransformConfig()
        elif isinstance(transform_config, dict):
            transform_config = pyine.organisms.datamodules.samples.configs.SampleTransformConfig(**transform_config)
        self.transform_config = transform_config
        if prompt_result_db_path is None:
            self.prompt_result_db = pyine.prompts.get_framework_db()
        else:
            self.prompt_result_db = pyine.prompts.PromptResultDB(prompt_result_db_path)
        self.readers_map, self.orig_traces = self._init_readers_and_trace_metadata(
            source_data=source_data,
            traces=traces,
        )
        self._prepare_sampling_data()

    @property
    def current_epoch(self) -> int:
        """Returns the epoch index currently used to build samples."""
        return self._curr_epoch

    def set_epoch(
        self,
        epoch: int,
    ) -> None:
        """Updates the builder's epoch, refreshing sampling data when it changes."""
        if epoch < 0:
            raise ValueError(f"epoch must be non-negative, got {epoch}")
        if epoch == self._curr_epoch:
            logger.debug("sample builder epoch already set; skipping refresh")
            return
        logger.info(f"updating sample builder (epoch changed from {self._curr_epoch} to {epoch})")
        self._curr_epoch = epoch
        self._prepare_sampling_data()

    @staticmethod
    def _init_readers_and_trace_metadata(
        source_data: pyine.data.traces.dataset_reader.DatasetOrDatasetPathObjectOrArray,
        traces: (list[pyine.data.traces.dataset_utils.TraceMetadata] | None),  # if none, targets all
    ) -> tuple[
        dict[str, pyine.data.traces.dataset_reader.DatasetProtocol],
        list[pyine.data.traces.dataset_utils.TraceMetadata],
    ]:
        """Initializes a list of LMDB readers and a list of target traces."""
        if isinstance(source_data, collections.abc.Sequence) and not isinstance(source_data, (str, pathlib.Path)):
            raw_source_items: list[typing.Any] = list(source_data)
        else:
            raw_source_items = [source_data]
        logger.debug(
            f"initializing readers and metadata for:\n\t{'\n\t'.join(str(source) for source in raw_source_items)}"
        )
        readers_map: dict[str, pyine.data.traces.dataset_reader.DatasetProtocol] = {}
        normalized_sources: list[pyine.data.traces.dataset_reader.DatasetProtocol] = []
        for raw_item in raw_source_items:
            if isinstance(raw_item, (str, pathlib.Path)):
                reader_obj = pyine.data.traces.dataset_reader.DatasetReader(pathlib.Path(raw_item))
            elif isinstance(raw_item, pyine.data.traces.dataset_reader.DatasetProtocol):
                reader_obj = raw_item
            else:
                raise TypeError(f"unsupported dataset source type: {type(raw_item)}")
            normalized_sources.append(reader_obj)
            readers_map[reader_obj.hash] = reader_obj
        assert len(readers_map) > 0, "sample builder initialization expects at least one data source"
        if traces is None:
            logger.debug("(targeting all available traces)")
            traces = pyine.data.traces.dataset_reader.get_traces_metadata(list(readers_map.values()))
        else:
            logger.debug(f"(targeting {len(traces)} traces)")
        assert isinstance(traces, list)
        assert all(t.parent_dataset_hash in readers_map for t in traces)
        assert all(0 <= trace_meta.index < len(readers_map[trace_meta.parent_dataset_hash]) for trace_meta in traces)
        return readers_map, traces

    def _prepare_sampling_data(self) -> None:
        """Prepares the data that will later be used to prepare data samples from the input dataset."""
        import pyine.organisms.datamodules.samples.filtering
        import pyine.organisms.datamodules.samples.selection

        logger.info("preparing sampling data...")
        logger.debug(
            f"epoch={self._curr_epoch};"
            f" targeting {len(self.orig_traces)} traces"
            f" across {len(self.readers_map)} datasets"
        )
        self.filtering_results = pyine.organisms.datamodules.samples.filtering.filter_traces(
            traces=self.orig_traces,
            epoch=self._curr_epoch,
            filtering_config=self.filtering_config,
        )
        logger.info(
            f"trace filtering: kept {self.filtering_results.kept_trace_count}"
            f" out of {self.filtering_results.orig_trace_count} traces"
            f" across {len(self.filtering_results.kept_trace_families)} trace families"
        )
        logger.debug(
            f"filtered {self.filtering_results.filtered_by_step_count} by step count,"
            f" {self.filtering_results.filtered_by_code_length} by code length,"
            f" {self.filtering_results.filtered_by_var_length} by var length,"
            f" {self.filtering_results.filtered_by_trace_family_cap} by trace family cap"
        )
        logger.info("preparing filtered dataset family/code-type-set mappings...")
        self.filtered_dataset_mappings = _samples_common.TraceDatasetToSampleCodeTypeMappings.create_from_traces(
            traces=self.filtering_results.kept_traces,
            prompt_result_db=self.prompt_result_db,
        )
        self.selection_results = pyine.organisms.datamodules.samples.selection.select_samples_from_trace_families(
            trace_data=self.filtered_dataset_mappings,
            epoch=self._curr_epoch,
            selection_config=self.selection_config,
            prompt_result_db=self.prompt_result_db,
        )
        selected_traces = self.selection_results.get_selected_traces()
        logger.info(
            f"sample selection: picked {len(self.selection_results)} samplesacross {len(selected_traces)} traces"
        )
        logger.debug(
            f"{self.selection_results.samples_with_full_trace_support} with full trace support,"
            f" {self.selection_results.samples_with_prompt_db_code} with prompt db code,"
            f" {self.selection_results.samples_with_parent_fallback} with parent fallback,"
            f" and {self.selection_results.failed_selections} failed selection attempts"
        )
        code_type_counts = collections.Counter([s.code_type for s in self.selection_results.samples])
        code_type_counts_str = "\n\t".join([f"{k}: {c}" for k, c in code_type_counts.items()])
        logger.debug(f"selected sample code types:\n\t{code_type_counts_str}")
        self.code_summaries = self._build_code_summaries_lut(
            traces=selected_traces,
            prompt_result_db=self.prompt_result_db,
        )
        logger.debug(f"fetched {len(self.code_summaries)} code summaries")
        logger.info(f"sampling data preparation complete ({len(self.selection_results)} samples)")

    @staticmethod
    def _build_code_summaries_lut(
        traces: list[pyine.data.traces.dataset_utils.TraceMetadata],
        prompt_result_db: pyine.prompts.PromptResultDB,
    ) -> dict[pyine.data.traces.dataset_utils.SolutionIdentifier, str]:  # sid to code description map
        """Builds a lookup table of code summaries for each trace."""
        code_summaries_lut: dict[
            pyine.data.traces.dataset_utils.SolutionIdentifier,
            str,
        ] = {}
        for trace_meta in traces:
            if trace_meta.solution_id not in code_summaries_lut:
                records = prompt_result_db.get_by_identifier(
                    identifier=str(trace_meta.solution_id),
                    prompt_name=pyine.prompts.names.PromptNames.CODE_SUMMARY,
                )
                if records:
                    # always take the latest summary that's available in the database
                    code_summaries_lut[trace_meta.solution_id] = records[-1].result
        logger.debug(f"found {len(code_summaries_lut)} code summaries in prompt result db")
        return code_summaries_lut

    def get_stats(self) -> dict[str, int | float | str]:
        """Returns a dictionary of statistics for the prepared samples."""
        # note: we cannot provide stats on the transformed samples as output types are resolved later
        stats: dict[str, int | float | str] = {
            "orig_trace_count": self.filtering_results.orig_trace_count,
            "kept_trace_count": self.filtering_results.kept_trace_count,
            "kept_trace_family_count": len(self.filtering_results.kept_trace_families),
            "filtered/by_step_count": self.filtering_results.filtered_by_step_count,
            "filtered/by_code_length": self.filtering_results.filtered_by_code_length,
            "filtered/by_var_length": self.filtering_results.filtered_by_var_length,
            "filtered/by_trace_family_cap": self.filtering_results.filtered_by_trace_family_cap,
            **{f"selected/type/{k}": c for k, c in self.selection_results.get_code_type_counts().items()},
            "selected/failed_selections": self.selection_results.failed_selections,
            "selected/with_full_trace_support": self.selection_results.samples_with_full_trace_support,
            "selected/with_prompt_db_code": self.selection_results.samples_with_prompt_db_code,
            "selected/with_parent_fallback": self.selection_results.samples_with_parent_fallback,
            "summaries_count": len(self.code_summaries),
            "sample_count": len(self.selection_results.samples),
        }
        return stats

    def __len__(self) -> int:
        """Returns the number of samples that will be generated (in the current epoch)."""
        return len(self.selection_results.samples)

    def __getitem__(self, idx: int) -> _samples_common.SampleData:
        """Returns the sample associated with a specified index (where `0 <= idx < len(self)`)."""
        import pyine.organisms.datamodules.samples.transform

        if not (0 <= idx < len(self)):
            raise IndexError(f"sample index {idx} is out of range")
        selected_sample = self.selection_results.samples[idx]
        reader = self.readers_map[selected_sample.trace_meta.parent_dataset_hash]
        trace_data = reader[selected_sample.trace_meta.index]
        transform_rng = self.transform_config.get_rng(sample=idx, epoch=self._curr_epoch)
        sample = pyine.organisms.datamodules.samples.transform.generate_sample(
            code_type_selection_result=selected_sample,
            trace_data=trace_data,
            code_summary=self.code_summaries.get(selected_sample.trace_meta.solution_id, ""),
            transform_config=self.transform_config,
            rng=transform_rng,
        )
        if sample is None:
            raise RuntimeError(
                f"failed to generate sample for idx={idx}"
                " (current sample builder impl should never produce a None sample,"
                " update transform config accordingly)"
            )
        # compute stats using sample here @@@@@
        # @@@@ consider caching results here too? (if they're expensive to compute, and not too voluminous?)
        return sample
